oro_menu_config:
    items:
        partner_list:
            label: 'orocrm.partner.entity_plural_label'
            route: 'orocrm_partner_index'
            extras:
                position: 50
                routes: ['orocrm_partner_*', 'github_accounts_list']

        github_accounts_list:
            label: 'orocrm.partner.githubaccount.entity_plural_label'
            route: 'orocrm_github_account_index'
            extras:
                position: 60

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        partner_list: ~
                        github_accounts_list: ~


oro_titles:
    orocrm_partner_index: ~
    orocrm_github_account_index: ~
