parameters:
    orocrm_partner.partner.entity.class:                        OroCRM\Bundle\PartnerBundle\Entity\Partner
    orocrm_partner.type.partner.class:                          OroCRM\Bundle\PartnerBundle\Form\Type\PartnerType
    orocrm_partner.form.type.partner_git_hub.class:             OroCRM\Bundle\PartnerBundle\Form\Type\PartnerGitHubType
    orocrm_partner.form.type.partner_git_hub_collection.class:  OroCRM\Bundle\PartnerBundle\Form\Type\PartnerGitHubCollectionType
    orocrm_partner.handler.partner.class:                       OroCRM\Bundle\PartnerBundle\Form\Handler\PartnerHandler

    orocrm_partner.partner.manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    orocrm_partner.type.partner.api.class:                      OroCRM\Bundle\PartnerBundle\Form\Type\PartnerApiType

    orocrm_partner.form.validator.unique_partner_account.class: OroCRM\Bundle\PartnerBundle\Validator\Constraints\UniquePartnerAccountValidator

    orocrm_partner.provider.configuration.class:                OroCRM\Bundle\PartnerBundle\Provider\ConfigurationProvider

services:
    orocrm_partner.form.partner:
        class:                                      Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [orocrm_partner_form, orocrm_partner]

    orocrm_partner.form.type.partner:
        class:                                      %orocrm_partner.type.partner.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: orocrm_partner }

    orocrm_partner.form.type.partner_git_hub:
        class: %orocrm_partner.form.type.partner_git_hub.class%
        tags:
             - { name: form.type, alias: oro_partner_git_hub }

    orocrm_partner.form.type.partner_git_hub_collection:
        class: %orocrm_partner.form.type.partner_git_hub_collection.class%
        tags:
             - { name: form.type, alias: oro_partner_git_hub_collection }

    orocrm_partner.form.handler.partner:
        class:                                      %orocrm_partner.handler.partner.class%
        scope: request
        arguments:
            - @orocrm_partner.form.partner
            - @request
            - @doctrine.orm.entity_manager

    orocrm_partner.partner.manager.api:
        class:                                      %orocrm_partner.partner.manager.api.class%
        arguments:
            - %orocrm_partner.partner.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_partner.form.type.partner.api:
        class:                                      %orocrm_partner.type.partner.api.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: orocrm_partner_api }

    orocrm_partner.form.partner.api:
        class:                                      Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [partner, orocrm_partner_api]

    orocrm_partner.form.handler.partner.api:
        class:                                      %orocrm_partner.handler.partner.class%
        scope: request
        arguments:
            - @orocrm_partner.form.partner.api
            - @request
            - @doctrine.orm.entity_manager

    orocrm_partner.form.validator.unique_partner_account:
        class: %orocrm_partner.form.validator.unique_partner_account.class%
        arguments:
            - @doctrine
        tags:
            - { name: validator.constraint_validator, alias: unique_partner_account }

    orocrm_partner.provider.configuration:
        class: %orocrm_partner.provider.configuration.class%
        arguments:
            - @oro_config.global
